<!DOCTYPE html>
<html>
    <head>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <title>html Editor</title>
    </head>
    <body>
        <div class='logo'>
            <b>
                <span class='brackets left'><</span>
                <span>html</span>
                <span class='brackets right'>></span>
            </b>
            Editor
        </div>

        <p class='sample'>This is the simple example of how HTML Editor works. You can change the code if you want.</p>
        
        <button id='button' onClick='changeTheme()'>Dark Theme</button>
    </body>
</html>

		
